# https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
#
# Contributors to the evolution of this form:
#
#  sunqm
#  fishjojo
#  mjw99
#  yangcal
#  maxscheurer
#
name: CI

#FIXME: workflow dependency not working on non-default branch?
#on:
#  workflow_run:
#    workflows:
#      - Lint
#    types:
#      - completed
on: [push, pull_request]

jobs:

  linux-build-aarch64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        #pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
        pyver: [cp38-cp38]
    env:
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Build Wheel
        run: |
            docker run --rm -v ${{ github.workspace }}:/src/pyscf:rw --workdir=/src/pyscf ${{ env.img }} \
            bash -exc '/opt/python/${{ matrix.pyver }}/bin/pip install --upgrade pip setuptools && \
            /opt/python/${{ matrix.pyver }}/bin/pip install "numpy!=1.16,!=1.17" "scipy!=1.5" h5py pytest pytest-cov pytest-timer pyberny geometric && \
            yum install -y epel-release && \
            yum-config-manager --enable epel && \
            yum install -y openblas-devel gcc cmake curl && \
            cd ./pyscf/lib && curl -o deps.tar.gz -L "https://github.com/kkyusuke/pyscf-build-deps/blob/master/pyscf-2.1a-aarch64-deps.tar.gz?raw=true"  && \
            tar xzf deps.tar.gz && \
            mkdir build && cd build && \
            cmake -DBUILD_LIBXC=OFF -DBUILD_XCFUN=OFF -DBUILD_LIBCINT=OFF .. && \
            make -j2 && cd .. && rm -Rf build && cd ../.. && \
            export OMP_NUM_THREADS=1 && export PYTHONPATH=$(pwd):$PYTHONPATH && \
            ulimit -s 20000 && /opt/python/${{ matrix.pyver }}/bin/pytest pyscf/ --ignore=pyscf/adc --ignore=pyscf/pbc/df --ignore=pyscf/pbc/cc -s -c setup.cfg --cov-report xml --cov-report term --cov-config .coveragerc --cov pyscf'
