# https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
#
# Contributors to the evolution of this form:
#
#  sunqm
#  fishjojo
#  mjw99
#  yangcal
#  maxscheurer
#
name: CI

#FIXME: workflow dependency not working on non-default branch?
#on:
#  workflow_run:
#    workflows:
#      - Lint
#    types:
#      - completed
on: [push, pull_request]

jobs:

  linux-build-aarch64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        #pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
        pyver: [cp38-cp38]
    env:
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Build Wheel
        run: |
            docker run --rm -v ${{ github.workspace }}:/src/pyscf:rw --workdir=/src/pyscf \
            ${{ env.img }} \
            bash -exc '/opt/python/${{ matrix.pyver }}/bin/pip install --upgrade pip setuptools && \
            yum install -y epel-release && \
            yum-config-manager --enable epel && \
            yum install -y openblas-devel gcc && \
            pwd && ls && uname -r'
